### ISSUE TITLE
💥 SciPy 1.15.0 support tracker

### ISSUE THREAD

**Issue by jorenham** [jorenham/scipy-stubs#250]
https://github.com/scipy/scipy/releases/tag/v1.15.0rc1

## Stubtest errors

These are currently ignored in a dedicated "allowlist":

https://github.com/jorenham/scipy-stubs/blob/master/.mypyignore-todo

Once this isn't needed anymore; `scipy-stubs` can be considered to be compatible with `scipy 1.15.0[rc1]`

## Release schedule

```mermaid
gantt
    title SciPy 1.15 Release Schedule
    axisFormat %Y-%m-%d

    branch 1.15.x                   : milestone, m1, 2024-12-06, 4m
    release 1.15.0rc1               : 2024-12-09, 25d
    release 1.15.0rc2 (if needed)   : 2024-12-20, 14d
    release 1.15.0                  : milestone, m2, 2025-01-03, 4m
```

## Checklist

These are the changes that are relevant to `scipy-stubs`. All of these are required for the `scipy-stubs 1.15.0.0` release.

- [x] `_lib` - [#331](https://github.com/jorenham/scipy-stubs/pull/331)
    - [x] ➕ ~`_array_api.*` - a bunch of  new exported members~
    - [x] ➕ `_util.{Generator,Seed}Type`
    - [x] ➕ `_docscrape.{ObjDoc,get_doc_object}`
    - [x] ♻️ `_array_api.Array[Like]` - moved out of `if TYPE_CHECKING`
    - [x] ❌ `_docscrape.{header,indent}`
- [x] `cluster` - [#334](https://github.com/jorenham/scipy-stubs/pull/334)
    - [x] ♻️ `hierarchy.ClusterNode.__init__` - `dist` param default changed from `0` to `0.0`
    - [x] 🎲 `vq.kmeans[2]`
- [x] `constants` - [#330](https://github.com/jorenham/scipy-stubs/pull/330)
    - [x] ♻️ ~`_codata.parse_constants_{2002to2014,2018toXXXX}` - new `exact_func` param~
    - [x] ❌ `_codata.exact_values`
    - [x] ❌ `_codata.{epsilon,mu}0`
- [x] `differentiate` ([#258](https://github.com/jorenham/scipy-stubs/issues/258)) - [#329](https://github.com/jorenham/scipy-stubs/pull/329)
    - [x] ➕ `derivative`
    - [x] ➕ `jacobian`
    - [x] ➕ `hessian`
- [x] `fft` - [#336](https://github.com/jorenham/scipy-stubs/pull/336)
    - [x] ➕ `_basic_backend.complex_funcs`
- [x] `fftpack` - [#336](https://github.com/jorenham/scipy-stubs/pull/336)
    - [x] ♻️ `_cache` - default changed from `{}` to `threading.local()`
- [x] `integrate` - [#337](https://github.com/jorenham/scipy-stubs/pull/337)
    - [x] ➕ `lebedev_rule`
    - [x] ➕ `nsum`
    - [x] ➕ `cubature`
    - [x] ➕ `tanhsinh`
    - [x] ♻️ `cumulative_trapezoid` - require `initial: {0, None}`
    - [x] ♻️ `simpson` - `x` param is now postitional- or keyword
    - [x] ❌ `AccuracyWarning` - see [scipy/scipy#22094](https://github.com/scipy/scipy/issues/22094)
    - [x] ❌ `quadrature`, `romberg`
- [x] `interpolate` - [#338](https://github.com/jorenham/scipy-stubs/pull/338)
    - [x] ➕ `AAA`
    - [x] ➕ `FloaterHormannInterpolator`
    - [x] ➕ `make_spl[p]rep`
    - [x] ➕ `generate_knots`
    - [x] ➕ `_interpnd.*` - renamed `interpnd.pyx` -> `_interpnd.pyx`
    - [x] ❌ `interpnd.*` - renamed `interpnd.pyx` -> `_interpnd.pyx`
    - [x] ♻️ `{Akima1D, Pchip}Interpolator` - disallow complex input
    - [x] ♻️ `BSpline.integrate` - always return array
    - [x] ♻️ `make_lsq_spline` - new `method: {"qr", "nowm-eq"}` kwarg
    - [x] ♻️ `NdBSpline.{k, t}` - attrs changed into props
    - [x] 🎲 `BarycentricInterpolator`, `barycentric_interpolate` 
- [x] `io` - [#341](https://github.com/jorenham/scipy-stubs/pull/341)
    - [x] ➕ `matlab.varmats_from_mat` - public re-export from `io.matlab._mio5`
    - [x] ♻️ `hb_read` - new `spmatrix: bool` kwarg
    - [x] ♻️ `loadmat` - new `spmatrix: bool` kwarg
    - [x] ♻️ `mmread` - new `spmatrix: bool` kwarg
    - [x] ♻️ `_idl.AttrDict` - `init` param changed to `None` as default
    - [x] ♻️ `_mmio.MMFile.read` - new `spmatrix: bool` kwarg
    - [x] ❌ `arff._arffread.basic_stats`
    - [x] ❌ `arff._arffread.print_attribute`
    - [x] ❌ `arff._arffread.test_weka`
- [x] `linalg` - [#344](https://github.com/jorenham/scipy-stubs/pull/344)
    - [x] ➕ ~`lapack.{lantr, {sy,he}trs, {tr,gt}con}`~
    - [x] ♻️ `orthogonal_procrustes` - accept complex input
    - [x] ♻️ `null_space` - new params:
        - `overwrite_a`
        - `check_finite`
        - `lapack_driver`
    - [x] ♻️ `solve` - `assume_a` accepts more literal strings:
        - `[tri]diagonal`
        - `banded`
        - `{upper,lower} triangular`
        - `sym[metric]`
        - `her[mitian]`
        - `pos[itive definite]`
        - `gen[eral]`
    - [x] ♻️ `_special_matrices` - batching of >2-d input
        - `circulant`
        - `companion`
        - `convolution_matrix`
        - `fiedler[_companion]`
        - `leslie`
    - [x] ♻️ `_matfuncs_expm.pade_UV_calc` - change to `(Am, m: int) -> int`
    - [x] 🗑️ `toeplitz` - >1-d input (currently raveled, will "batch" in 1.17+)
    - [x] 🗑️ `kron`
    - [x] 🗑️ `interpolative.{rand,seed}`
    - [x] 🎲 `clarkson_woodruff_transform`
    - [x] 🎲 `_sketches.cwt_matrix`
    - [x] 🎲 `interpolative.interp_decomp`
    - [x] 🎲 `interpolative.svd`
    - [x] 🎲 `interpolative.estimate_spectral_norm[_diff]`
    - [x] 🎲 `interpolative.estimate_rank`
- [x] `misc` (🗑️) - [#328](https://github.com/jorenham/scipy-stubs/pull/328)
    - [x] ❌ everything (but keep an empty `__init__`)
- [x] `ndimage` - [#346](https://github.com/jorenham/scipy-stubs/pull/346)
    - [x] ♻️ `correlate`, `convolve`, `laplace` - new `axes` param 
    - [x] ♻️ `generic_{laplace, gradient_magnitude,filter}` - new `axes` param 
    - [x] ♻️ `gaussian_{laplace, gradient_magnitude}` - new `axes` param hosts~
- [x] `optimize` - [#347](https://github.com/jorenham/scipy-stubs/pull/347)
    - [x] ➕ `elementwise.{bracket, find}_{root, minimum}`
    - [x] ➕ `HessianUpdateStrategy.__matmul__`
    - [x] ♻️ `differential_evolution` - accepts map-like callable for `workers`
    - [x] ♻️ `_trustregion_constr.{BarrierSubproblem, tr_interior_point}` - new *required* `finite_diff_bounds` arg
    - [x] 🎲 `basinhopping`
    - [x] 🎲 `differential_evolution` 
    - [x] 🎲 `dual_annealing`
    - [x] 🎲 `check_grad`
    - [x] 🎲 `quadratic_assignment`
- [x] `signal` - [#348](https://github.com/jorenham/scipy-stubs/pull/348)
    - [x] ➕ `envelope`
    - [x] ➕ `freqz_sos` (previously `sosfreqz`)
    - [x] ♻️ `sosfreqz` - now an alias of `freqz_sos`
    - [x] ♻️ `chirp` - accept complex input
    - [x] ♻️ `lombscargle`
        - add `weights` param 
        - add `floating_mean` param
        - change `normalize` param
    - [x] 🗑️ `correlate`, `convolve`, `choose_conv_method` - `object_` and `longdouble` input
    - [x] 🗑️ `lfilter`, `sosfilt` - `object_` and `longdouble` input
    - [x] ❌ `cmplx_sort`
    - [x] ❌ `daub`, `qmf`, `cascade`, `morlet[2]`, `ricker`, `cwt`
    - [x] ❌ `_spectral` (pythran module)
- [x] `sparse` - [#349](https://github.com/jorenham/scipy-stubs/pull/349)
    - [x] ➕ `coo_{array,matrix}.tensordot(other, axes=2)`
    - [x] ➕ `safely_cast_index_arrays`, `get_index_dtype`
    - [x] ➕ `linalg.{spbandwidth, is_sptriangular}`
    - [x] ♻️ `linalg.*` - support `sparray`
    - [x] ♻️ `csgraph.*` - support `sparray`
    - [x] ♻️ `csgraph.min_weight_full_bipartite_matching` - arg `biadjacency_matrix` changed to `biadjacency`
    - [x] ♻️ `_base._spbase.__init__` - `maxprint` is now keyword-only
    - [x] ♻️ `coo_array` - support >=1-D data
    - [x] ♻️ `sp{array,matrix}` - disallow `float16` and other incompatible dtypes
    - [x] ♻️ `sp{array,matrix}.count_nonzero` - new `axis` arg
    - [x] ♻️ `[arg]{min,max}` - new `explicit` param
    - [x] ♻️ `_sputils.{check_shape,isshape}` - arg `allow_1d` changed to `allow_nd`
    - [x] 🎲 `rand[om[_array]]`
    - [x] 🎲 `linalg.svds`
- [x] `spatial` - [#350](https://github.com/jorenham/scipy-stubs/pull/350)
    - [x] ♻️ `Rotation.concatenate` - accept a bare `Rotation` object and returns a copy
    - [x] 🗑️ `distance.{cosine, correlation}` - deprecate complex input
    - [x] 🗑️ `distance.{kulczynski1, sokalmichener}` - will be removed in 1.17
    - [x] 🎲 `distance.directed_hausdorff`
    - [x] 🎲 `transform.Rotation.random` 
- [x] `special` - [#351](https://github.com/jorenham/scipy-stubs/pull/351)
    - [x] ➕ `_spherical_bessel.{spherical_kn_reflection, use_reflection}` (private, but no `__all__`)
    - [x] ➕ `softplus`
    - [x] ➕ `legendre_p[_all]`
    - [x] ➕ `assoc_legendre_p[_all]`
    - [x] ➕ `sph_legendre_p[_all]`
    - [x] ➕ `sph_harm_y[_all]`
    - [x] ♻️ `factorial[{2, k}]}` - accept complex input when `extend: {"complex"}`
    - [x] ♻️ `factorial` - disallow non-integer input if `exact: {True}`
    - [x] ♻️ `factorialk` - default to `exact=False`
    - [x] ♻️ `zeta` - to support complex
    - [x] ♻️ ~`gdtrib` - GPU support for cupy's `ElementwiseKernel`~
    - [x] 🗑️ `lpn`, `lpmn`, `clpmn` (see also [scipy#22160](https://github.com/scipy/scipy/pull/22160))
    - [x] 🗑️ `sph_harm` - [#369](https://github.com/jorenham/scipy-stubs/issues/369)
    - [x] ❌ `btdtr[i]`
- [x] `stats` - [#353](https://github.com/jorenham/scipy-stubs/pull/353)
    - [x] ➕ new distribution infrastructure ([#260](https://github.com/jorenham/scipy-stubs/issues/260)) - [#360](https://github.com/jorenham/scipy-stubs/pull/360)
        - [x] ➕ `Normal`
        - [x] ➕ `Uniform`
        - [x] ➕ `Mixture`
        - [x] ➕ `make_distribution`
        - [x] ➕ `exp`, `log`
        - [x] ➕ `abs`
        - [x] ➕ `truncate`
        - [x] ➕ `order_statistic`
    - [x] ➕ `lmoment` (🎖️)
    - [x] ➕ `chatterjeexi`
    - [x] ➕ `dpareto_lognorm`, `landau`, `normal_inverse_gamma`, `poisson_binom` (distrs)
    - [x] ♻️ `chi2_contingency`, `ttest_ind`, `fisher_exact` - new `method` kw-only param
    - [x] ♻️ `ttest_ind` - all params except `a` and `b` are keyword-only
    - [x] ♻️ `chisquare` - new `sum_check` kw-only param
    - [x] ♻️ `wilcoxon` - accept `method="asymptotic"`
    - [x] ♻️ `fisher_exact` - 2-d tables with shapes other than `(2,2)`
    - [x] ❌ `rvs_ratio_uniforms`
    - [x] ❌ `sampling` (unannounced breaking change?)
    - [x] 🗑️ `find_repeats`
    - [x] 🗑️ `trapz`
    - [x] 🗑️ `linregress` - deprecate single-argument usage
    - [x] 🗑️ `ttest_ind` - deprecate `random_state` and `permutations`
    - [x] 🎲 `{Bootstrap,Permutation}Method`
    - [x] 🎲 `bootstrap`, `permutation_test`
    - [x] 🎲 `goodness_of_fit`
    - [x] 🎲 `dunnett`
    - [x] 🎲 `sobol_indices`
    - [x] 🎲 `qmc.*` - all classes that consume random numbers
- [x] `version` - [#345](https://github.com/jorenham/scipy-stubs/pull/345)
    - [x] ❌ `commit_count` (see [scipy/scipy#22102](https://github.com/scipy/scipy/issues/22102))

Sources:

- https://github.com/scipy/scipy/wiki/*-Release-Note-Entries-for-SciPy-1.15.0-(asterisk-makes-this-appear-at-the-top)#scipy-1150-release-notes
- https://github.com/scipy/scipy/pull/21982
- https://github.com/scipy/scipy/issues/15765

### Legend

- ➕ - added, exposed, or renamed to this (i.e. did not exist before)
- ♻️ - changed
- 🗑️ - deprecate (usually until 1.17)
- ❌ - remove (pending deprecation or private rename)
- 🎲 - add [SPEC 7](https://scientific-python.org/specs/spec-0007/) `rng` parameter (#257)

**Comment by jorenham** [comment]
note to self: branch `scipy/1.15.0rc1` once it releases

**Comment by tylerjereddy** [comment]
Looks very organized! In case it isn't obvious, I may be slightly delayed on the exact days for branching and RC1.

**Comment by jorenham** [comment]
> Looks very organized! 

Thanks :)

> In case it isn't obvious, I may be slightly delayed on the exact days for branching and RC1.

No problem! 
I'll try my best to sync the `scipy-stubs` 1.15.0.0  with the `scipy` 1.15.9 one as much as possible. And I expect that the RC window of 4 weeks should be more than enough for that 👌🏻.

**Comment by jorenham** [comment]
everything appears to be valid with `1.15.0rc2` now, too 👌🏻
