### ISSUE TITLE
🌕 complete `scipy.signal`

### ISSUE THREAD

**Issue by jorenham** [jorenham/scipy-stubs#99]
it uses `Untyped*` ~662~ ~628~ ~623~ ~517~ ~506~ ~453~ ~296~ ~186~ 156 times

- [x] `_arraytools`
- [x] `_spline_filters` (`_bsplines` in `scipy<1.15`)
- [x] `_czt`
- [x] `_filter_design` - #378
- [x] `_fir_filter_design` - #384
- [x] `_lti_conversion`
- [x] `_ltisys` - #185
- [x] `_max_len_seq_inner`
- [x] `_max_len_seq` - #384
- [x] `_peak_finding` - #87
- [x] `_peak_finding_utils`
- [x] `_savitzky_golay` - #124
- [x] `_short_time_fft` - #226 
- [x] `_signaltools` - #379
- [x] `_spectral`
- [x] `_spectral_py` - #157
- [x] `_spline` - #348
- [x] `_upfirdn`
- [x] `_waveforms`
- [x] `_wavelets` - #195
- [x] `windows._windows` - #153

**Comment by jorenham** [comment]
Once #157 is merged we'll be at 517

**Comment by jorenham** [comment]
@pavyamsiri are you currently working on a particular module or something? Because I'd like to work on this as well, and we should probably avoid a situation where we're both working on the same code.

**Comment by pavyamsiri** [comment]
Not currently no. The remaining modules have a lot of functions in them so I haven't done any work on them yet. I'm not sure when I'll get back to working on this yet so you can have free reign over which ones you want to work on.

**Comment by jorenham** [comment]
> Not currently no. 

Ok, no problem! If there's anything specific you'd like to work on, let me knoow, and I'll "reserve" it for you :)

> The remaining modules have a lot of functions in them so I haven't done any work on them yet. 

Yea there are a couple of real "plus-sized" modules left 😅. It's probably a good idea to split those up. At first glance there appear to be some natural clusters of functions in e.g. `_filter_design` and `_signaltools`, so I guess that could help.

FYI, I'd also gladly accept single-function "coffee-break" PR's 😄.
